//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDtl
    {
        public int OrderDtlsId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> EmpID { get; set; }
        [Required]
        [Display(Name = "Quentity")]
        [DataType(DataType.PhoneNumber)]
        public string Quentity { get; set; }
        [Required]
        [Display(Name = "TotalCost")]
        [DataType(DataType.PhoneNumber)]
        public string TotalCost { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
