//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDtls = new HashSet<OrderDtl>();
        }
    
        public int OrderId { get; set; }
        [Required]
        [Display(Name = "Order Date")]
        [DataType(DataType.Date)]
        public string Orderdate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ShippingId { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDtl> OrderDtls { get; set; }
        public virtual ShippingInfo ShippingInfo { get; set; }
    }
}
