//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDtls = new HashSet<OrderDtl>();
        }
    
        public int ProductId { get; set; }
        [Required]
        [Display(Name = "ProductName")]
        [StringLength(50)]
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        [Required]
        [Display(Name = "Price")]
        [DataType(DataType.PhoneNumber)]
        public string price { get; set; }
        public string ImageFile { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDtl> OrderDtls { get; set; }
    }
}
