//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShippingInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingInfo()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ShippingId { get; set; }
        public Nullable<int> DeliveryBoyId { get; set; }
        [Required]
        [Display(Name = "Shipping Cost")]
        [DataType(DataType.PhoneNumber)]
        public string ShippingCost { get; set; }
        [Required]
        [Display(Name = "Shipping Date")]
        [DataType(DataType.Date)]
        public string ShippingDate { get; set; }

        public virtual DeliveryBoy DeliveryBoy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
